use std::borrow::Cow;
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};

use rmcp::model::{
    CallToolRequestParams, CallToolResult, ContentBlock, Implementation, ListToolsResult,
    PaginatedRequestParams, ServerCapabilities, ServerInfo, Tool,
};
use rmcp::{ErrorData as McpError, RoleServer, ServerHandler};
use xai_grok_tools::types::definition::ToolDefinition;

use crate::{
    ApprovalDecision, ApprovalRequest, GatewayEvent, GatewayPermissionDecision, GatewaySession,
};

/// MCP protocol adapter. Transport is intentionally outside this type so it
/// can be used with stdio now and Streamable HTTP later.
pub struct GatewayServer {
    session: Arc<GatewaySession>,
    call_sequence: AtomicU64,
}

impl Drop for GatewayServer {
    fn drop(&mut self) {
        self.session
            .event_bus()
            .emit(GatewayEvent::ClientDisconnected);
    }
}

impl GatewayServer {
    pub fn new(session: GatewaySession) -> Self {
        Self::from_shared_session(Arc::new(session))
    }

    /// Create a protocol handler over a retained gateway session.
    ///
    /// Streamable HTTP invokes this once per MCP protocol session; every
    /// handler shares the same toolset and permission policy.
    pub fn from_shared_session(session: Arc<GatewaySession>) -> Self {
        Self {
            session,
            call_sequence: AtomicU64::new(1),
        }
    }

    pub fn session(&self) -> &Arc<GatewaySession> {
        &self.session
    }

    fn mcp_tool(definition: ToolDefinition) -> Tool {
        let mut tool = Tool::default();
        tool.name = Cow::Owned(definition.function.name);
        tool.description = definition.function.description.map(Cow::Owned);
        // Definitions are generated by the finalized registry. An enabled
        // Grok tool always has an object JSON Schema; if that invariant ever
        // changes, do not invent a replacement schema here.
        tool.input_schema = Arc::new(
            definition
                .function
                .parameters
                .as_object()
                .cloned()
                .expect("finalized Grok tool definition must have object schema"),
        );
        tool
    }

    fn tools(&self) -> Vec<Tool> {
        self.session
            .toolset()
            .tool_definitions()
            .into_iter()
            .map(Self::mcp_tool)
            .collect()
    }
}

impl ServerHandler for GatewayServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_tool_list_changed()
                .build(),
        )
            .with_server_info(Implementation::new(
                "xai-grok-mcp-server",
                env!("CARGO_PKG_VERSION"),
            ))
            .with_instructions("Provides sandboxed local Grok Build coding tools and explicitly configured downstream MCP tools.")
    }

    async fn list_tools(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: rmcp::service::RequestContext<RoleServer>,
    ) -> Result<ListToolsResult, McpError> {
        Ok(ListToolsResult {
            tools: self.tools(),
            next_cursor: None,
            meta: None,
        })
    }

    async fn call_tool(
        &self,
        request: CallToolRequestParams,
        context: rmcp::service::RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let tool_name = request.name.as_ref();
        let arguments = serde_json::Value::Object(request.arguments.unwrap_or_default());
        let call_id = format!(
            "mcp-gateway-{}",
            self.call_sequence.fetch_add(1, Ordering::Relaxed)
        );
        self.session
            .event_bus()
            .emit(GatewayEvent::ToolCallStarted {
                call_id: call_id.clone(),
                tool_name: tool_name.to_string(),
                summary: observer_summary(tool_name, &arguments),
                details: observer_details(tool_name, &arguments),
            });

        let input = match self
            .session
            .toolset()
            .try_parse(tool_name, &arguments)
            .await
        {
            Ok(input) => input,
            Err(error) => {
                self.failed(&call_id, tool_name, "tool unavailable");
                return Ok(CallToolResult::error(vec![ContentBlock::text(format!(
                    "Tool `{tool_name}` is not available: {error}"
                ))]));
            }
        };
        let decision = self.session.permission().evaluate(tool_name, &input);
        if decision == GatewayPermissionDecision::Ask {
            self.session
                .event_bus()
                .emit(GatewayEvent::ApprovalRequested {
                    call_id: call_id.clone(),
                    tool_name: tool_name.to_string(),
                });
            let approval = self
                .session
                .request_approval(
                    ApprovalRequest {
                        call_id: call_id.clone(),
                        tool_name: tool_name.to_string(),
                        summary: approval_summary(tool_name, &arguments),
                    },
                    context.ct.clone(),
                )
                .await;
            let allowed = approval == ApprovalDecision::AllowOnce && !context.ct.is_cancelled();
            self.session
                .event_bus()
                .emit(GatewayEvent::ApprovalResolved {
                    call_id: call_id.clone(),
                    tool_name: tool_name.to_string(),
                    allowed,
                });
            if !allowed {
                self.failed(
                    &call_id,
                    tool_name,
                    "approval denied, timed out, or cancelled",
                );
                return Ok(CallToolResult::error(vec![ContentBlock::text(format!(
                    "Tool `{tool_name}` was denied by the gateway approval policy"
                ))]));
            }
        } else if decision != GatewayPermissionDecision::Allow {
            self.failed(&call_id, tool_name, "permission denied");
            return Ok(CallToolResult::error(vec![ContentBlock::text(format!(
                "Tool `{tool_name}` was denied by the gateway permission policy"
            ))]));
        }
        match self
            .session
            .toolset()
            .call(tool_name, arguments, &call_id, None)
            .await
        {
            Ok(result) => {
                let output = observer_tool_output(&result.prompt_text);
                self.session
                    .event_bus()
                    .emit(GatewayEvent::ToolCallFinished {
                        call_id,
                        tool_name: tool_name.to_string(),
                        output,
                    });
                Ok(CallToolResult::success(vec![ContentBlock::text(
                    result.prompt_text,
                )]))
            }
            Err(error) => {
                self.failed(&call_id, tool_name, "tool execution failed");
                Ok(CallToolResult::error(vec![ContentBlock::text(
                    error.to_string(),
                )]))
            }
        }
    }

    fn on_initialized(
        &self,
        context: rmcp::service::NotificationContext<RoleServer>,
    ) -> impl std::future::Future<Output = ()> + Send + '_ {
        self.session.event_bus().emit(GatewayEvent::ClientConnected);
        let mut catalog_changes = self.session.subscribe_catalog_changes();
        let peer = context.peer.clone();
        tokio::spawn(async move {
            while catalog_changes.recv().await.is_ok() {
                if peer.notify_tool_list_changed().await.is_err() {
                    break;
                }
            }
        });
        std::future::ready(())
    }
}

impl GatewayServer {
    fn failed(&self, call_id: &str, tool_name: &str, reason: &str) {
        self.session.event_bus().emit(GatewayEvent::ToolCallFailed {
            call_id: call_id.to_string(),
            tool_name: tool_name.to_string(),
            reason: reason.to_string(),
        });
    }
}

fn approval_summary(tool_name: &str, arguments: &serde_json::Value) -> String {
    let command = arguments.get("command").and_then(serde_json::Value::as_str);
    match command {
        Some(command) => format!("{}", command.chars().take(240).collect::<String>()),
        None => format!("{tool_name} requires local approval"),
    }
}

fn observer_summary(tool_name: &str, arguments: &serde_json::Value) -> String {
    let string = |names: &[&str]| {
        names
            .iter()
            .find_map(|name| arguments.get(*name).and_then(serde_json::Value::as_str))
    };
    let path = || {
        string(&[
            "target_directory",
            "target_file",
            "directory",
            "path",
            "file_path",
            "file",
        ])
    };
    let summary = match tool_name {
        "list_dir" | "ls" => path().map(str::to_owned),
        "read_file" | "read" => path().map(str::to_owned),
        "grep" | "search" => {
            let target = string(&["path", "target_directory", "directory"]);
            string(&["pattern", "query"]).map(|pattern| match target {
                Some(target) => format!("{pattern:?} in {target}"),
                None => format!("{pattern:?}"),
            })
        }
        "glob" => string(&["pattern", "glob", "path"]).map(str::to_owned),
        "run_terminal_cmd" | "run_terminal_command" | "bash" | "shell" | "execute" => {
            string(&["command"]).map(str::to_owned)
        }
        "search_replace" | "edit" | "apply_patch" | "strreplace" | "write" => {
            path().map(str::to_owned)
        }
        _ => {
            string(&["command", "path", "file_path", "query", "pattern", "glob"]).map(str::to_owned)
        }
    };
    crate::events::redact_observer_text(summary.as_deref().unwrap_or(tool_name), 240)
}

fn observer_details(
    tool_name: &str,
    arguments: &serde_json::Value,
) -> Option<crate::events::ObserverToolDetails> {
    use crate::events::{ObserverToolDetails, redact_observer_multiline};

    let string = |name| arguments.get(name).and_then(serde_json::Value::as_str);
    let path = || {
        string("file_path")
            .or_else(|| string("target_file"))
            .or_else(|| string("path"))
    };
    match tool_name {
        "search_replace" | "edit" | "strreplace" => Some(ObserverToolDetails::Edit {
            path: path()?.to_owned(),
            old_text: redact_observer_multiline(string("old_string")?, 8 * 1024),
            new_text: redact_observer_multiline(string("new_string")?, 8 * 1024),
        }),
        "write" => Some(ObserverToolDetails::Write {
            path: path()?.to_owned(),
            content: redact_observer_multiline(string("content")?, 8 * 1024),
        }),
        _ => None,
    }
}

fn observer_tool_output(output: &str) -> Option<String> {
    Some(crate::events::redact_observer_multiline(output, 8 * 1024))
        .filter(|output| !output.is_empty())
}

#[cfg(test)]
mod tests {
    use super::observer_summary;
    use serde_json::json;

    #[test]
    fn observer_summary_uses_list_dir_target_directory() {
        assert_eq!(
            observer_summary("list_dir", &json!({"target_directory": ".grok/docs"})),
            ".grok/docs"
        );
    }

    #[test]
    fn observer_summary_uses_read_file_target_file() {
        assert_eq!(
            observer_summary("read_file", &json!({"target_file": "/etc/os-release"})),
            "/etc/os-release"
        );
    }

    #[test]
    fn observer_summary_keeps_search_target_and_pattern() {
        assert_eq!(
            observer_summary(
                "grep",
                &json!({"pattern": "approval", "path": ".grok/docs"}),
            ),
            "\"approval\" in .grok/docs"
        );
    }
}
