use std::borrow::Cow;
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};

use rmcp::model::{
    CallToolRequestParams, CallToolResult, ContentBlock, Implementation, ListToolsResult,
    PaginatedRequestParams, ServerCapabilities, ServerInfo, Tool,
};
use rmcp::{ErrorData as McpError, RoleServer, ServerHandler};
use xai_grok_tools::types::definition::ToolDefinition;

use crate::{GatewayPermissionDecision, GatewaySession};

/// MCP protocol adapter. Transport is intentionally outside this type so it
/// can be used with stdio now and Streamable HTTP later.
pub struct GatewayServer {
    session: Arc<GatewaySession>,
    call_sequence: AtomicU64,
}

impl GatewayServer {
    pub fn new(session: GatewaySession) -> Self {
        Self::from_shared_session(Arc::new(session))
    }

    /// Create a protocol handler over a retained gateway session.
    ///
    /// Streamable HTTP invokes this once per MCP protocol session; every
    /// handler shares the same toolset and permission policy.
    pub fn from_shared_session(session: Arc<GatewaySession>) -> Self {
        Self {
            session,
            call_sequence: AtomicU64::new(1),
        }
    }

    pub fn session(&self) -> &Arc<GatewaySession> {
        &self.session
    }

    fn mcp_tool(definition: ToolDefinition) -> Tool {
        let mut tool = Tool::default();
        tool.name = Cow::Owned(definition.function.name);
        tool.description = definition.function.description.map(Cow::Owned);
        // Definitions are generated by the finalized registry. An enabled
        // Grok tool always has an object JSON Schema; if that invariant ever
        // changes, do not invent a replacement schema here.
        tool.input_schema = Arc::new(
            definition
                .function
                .parameters
                .as_object()
                .cloned()
                .expect("finalized Grok tool definition must have object schema"),
        );
        tool
    }

    fn tools(&self) -> Vec<Tool> {
        self.session
            .toolset()
            .tool_definitions()
            .into_iter()
            .map(Self::mcp_tool)
            .collect()
    }
}

impl ServerHandler for GatewayServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new(
                "xai-grok-mcp-server",
                env!("CARGO_PKG_VERSION"),
            ))
            .with_instructions("Provides sandboxed local Grok Build coding tools and explicitly configured downstream MCP tools.")
    }

    async fn list_tools(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: rmcp::service::RequestContext<RoleServer>,
    ) -> Result<ListToolsResult, McpError> {
        Ok(ListToolsResult {
            tools: self.tools(),
            next_cursor: None,
            meta: None,
        })
    }

    async fn call_tool(
        &self,
        request: CallToolRequestParams,
        _context: rmcp::service::RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let tool_name = request.name.as_ref();
        let arguments = serde_json::Value::Object(request.arguments.unwrap_or_default());

        let input = match self
            .session
            .toolset()
            .try_parse(tool_name, &arguments)
            .await
        {
            Ok(input) => input,
            Err(error) => {
                return Ok(CallToolResult::error(vec![ContentBlock::text(format!(
                    "Tool `{tool_name}` is not available: {error}"
                ))]));
            }
        };
        if self.session.permission().evaluate(tool_name, &input) != GatewayPermissionDecision::Allow
        {
            return Ok(CallToolResult::error(vec![ContentBlock::text(format!(
                "Tool `{tool_name}` was denied by the gateway permission policy"
            ))]));
        }

        let call_id = format!(
            "mcp-gateway-{}",
            self.call_sequence.fetch_add(1, Ordering::Relaxed)
        );
        match self
            .session
            .toolset()
            .call(tool_name, arguments, &call_id, None)
            .await
        {
            Ok(result) => Ok(CallToolResult::success(vec![ContentBlock::text(
                result.prompt_text,
            )])),
            Err(error) => Ok(CallToolResult::error(vec![ContentBlock::text(
                error.to_string(),
            )])),
        }
    }
}
